### PR TITLE
Add Wolverine, Storm, Mojo

### PR DESCRIPTION
**Pull request by gnkatchmar**
Add Wolverine, Storm, Mojo. Spiral & Mojo scenarios will need reprogramming to randomize Mojo Pack-specific modules; for now, they are set to have 0 modules.

### CODE REVIEW

**Comment by Naouak** [comment]
Thanks for all the work, I'm still waiting for my copy of those to arrive.

I'm gonna check what I can do regarding Mojo scenarios generation tomorrow. 

Can you replace the Hero cards pic with the one from FFG articles?

**Comment by gnkatchmar** [comment]
> 

Unsure what you mean by FFG articles? I've been using pics from the Hall of Heroes site. You can email me direct at gunk55@msn.com to clarify.

**Comment by Naouak** [comment]
You can find them here: 

 - https://www.fantasyflightgames.com/en/news/2022/8/18/tearing-it-up/
 - https://www.fantasyflightgames.com/en/news/2022/9/8/thunderstruck/
 - https://www.fantasyflightgames.com/en/news/2022/8/11/mojomania/ (for mojo, I think there's at least one of the module in this one)

**Comment by Naouak** [comment]
See #61

**Pull request closed without merging**
